---
environment_name: dev
aws_region: us-east-1

grafana_port: 3000
grafana_admin_user: admin
grafana_admin_password: admin
grafana_efs_mount_point: /var/lib/grafana
grafana_efs_file_system_id: ""

grafana_user: grafana
grafana_group: grafana
grafana_config_file: /etc/grafana/grafana.ini

prometheus_version: 2.53.0
prometheus_port: 9090
prometheus_scrape_interval: 15s
prometheus_retention_time: 15d
prometheus_data_dir: /prometheus-data
prometheus_config_dir: /etc/prometheus
prometheus_ec2_sd_enabled: true
prometheus_install_dir: /opt/prometheus-{{ prometheus_version }}
prometheus_current_dir: /opt/prometheus
prometheus_user: prometheus
prometheus_group: prometheus

node_exporter_version: 1.8.2
node_exporter_port: 9100
node_exporter_archive: "node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
node_exporter_install_dir: /opt/node_exporter-{{ node_exporter_version }}
node_exporter_current_dir: /opt/node_exporter
node_exporter_user: node_exporter
node_exporter_group: node_exporter

service_restart_policy: always
service_restart_delay: 5
log_level: info

grafana_static_targets: []
node_exporter_static_targets: []

alertmanager_version: 0.27.0
alertmanager_port: 9093
# Set this to your real webhook URL (Slack, PagerDuty, etc.)
alertmanager_webhook_url: ""

enable_firewall: false

ansible_user: ec2-user
ansible_ssh_private_key_file: ~/.ssh/prometheus-grafana.pem
ansible_python_interpreter: auto_silent
bastion_ip: ""

